# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d9443ae0e772994fa864a15b69cecee1"
name = "promotional-banner-app"
application_url = "https://me-petersburg-literacy-transmission.trycloudflare.com"
embedded = true
handle = "promotional-banner-app-13"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://me-petersburg-literacy-transmission.trycloudflare.com/auth/callback", "https://me-petersburg-literacy-transmission.trycloudflare.com/auth/shopify/callback", "https://me-petersburg-literacy-transmission.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
